CREATE TABLE file (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(300), mime VARCHAR(100), size REAL, telegram_id INTEGER, directory_id INTEGER, user_id INTEGER);
CREATE TABLE directory (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(300), parent_directory_id INTEGER, user_id INTEGER);
CREATE TABLE user (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(100), telegram_id INTEGER);